// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

/**
 * 
 */


namespace GateGameplayTags
{
    // === 屬性標籤 ===
    PROJECTGATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Health);
    PROJECTGATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_MaxHealth);
    PROJECTGATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_ActionPoints);
    PROJECTGATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_MaxActionPoints);
    PROJECTGATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_AttackPower);
    PROJECTGATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Defense);
    PROJECTGATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Initiative);

    // === 技能標籤 ===
    PROJECTGATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_BasicAttack);
    PROJECTGATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_RangedAttack);
    PROJECTGATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Heal);
    PROJECTGATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Fireball);
    PROJECTGATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Shield);

    // === 技能分類標籤 ===
    PROJECTGATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Type_Melee);
    PROJECTGATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Type_Ranged);
    PROJECTGATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Type_Magic);
    PROJECTGATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Type_Support);

    // === 冷卻標籤 ===
    PROJECTGATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_BasicAttack);
    PROJECTGATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_RangedAttack);
    PROJECTGATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Heal);
    PROJECTGATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Fireball);

    // === 效果標籤 ===
    PROJECTGATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_Damage);
    PROJECTGATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_Heal);
    PROJECTGATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_Buff);
    PROJECTGATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_Debuff);
    PROJECTGATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_Shield);
    PROJECTGATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_Burn);
    PROJECTGATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_Stun);

    // === 狀態標籤 ===
    PROJECTGATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);
    PROJECTGATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Stunned);
    PROJECTGATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Burning);
    PROJECTGATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Shielded);
    PROJECTGATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_InCombat);

    // === 動畫標籤 ===
    PROJECTGATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Animation_Attack_Melee);
    PROJECTGATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Animation_Attack_Ranged);
    PROJECTGATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Animation_Cast);
    PROJECTGATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Animation_Hit);
    PROJECTGATE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Animation_Death);
}